services:
  # Service de base de données
  tasks-db:
    image: postgres:15
    user: postgres
    secrets:
      - tasks-db-password
    env_file:
      - ./tasks-db/.env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - big_deal

  service-gestion-utilisateurs:
    build: ./service-gestion-utilisateurs
    env_file:
      - ./service-gestion-utilisateurs/.env
    depends_on:
      tasks-db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./service-gestion-utilisateurs
          target: /app
    #ports:
      #- 7080:8080
    expose:
      - 8080
    networks:
      - big_deal


  service-api:
    build: ./service-api
    env_file:
      - ./service-api/.env
    depends_on:
      tasks-db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./service-api
          target: /app
    #ports:
      #- 7081:8080
    expose:
      - 8080
    networks:
      - big_deal

  service-recommandation:
    build: ./service-recommandation
    env_file:
      - ./service-recommandation/.env
    depends_on:
      tasks-db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./service-recommandation
          target: /app
    #ports:
      #- 7083:8080
    expose:
      - 8080
    networks:
      - big_deal
    volumes:
      - ./service-recommandation/documents:/app/documents


  service-pari:
    build: ./service-pari
    env_file:
      - ./service-pari/.env
    depends_on:
      tasks-db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./service-pari
          target: /app
    #ports:
       #- 6080:8080
    expose:
      - 8080
    networks:
      - big_deal

  gateway-service:
    build: ./gateway-service
    env_file:
      - ./gateway-service/.env
    develop:
      watch:
        - action: rebuild
          path: ./gateway-service
          target: /app
    ports:
      - 8888:8080
    networks:
      - big_deal

  adminer:
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=tasks-db
    ports:
      - 9080:8080
    networks:
      - big_deal

secrets:
  tasks-db-password:
    file: secrets/tasks-db-password
  auth-db-password:
    file: secrets/auth-db-password

networks:
  big_deal:
    driver: bridge
